[http]
host = "127.0.0.1"
port = 2727

[amqp]
host = "localhost"
port = 5672

[grpc]
# ca_cert = "assets/certs/ca.crt"
# domain_name = "name-on-the-server-cert"
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"

[mqtt]
client_id = "TaskOrchestrator-MQTT"
host = "localhost"
port = 1883

[amqp.consumer]
exchange = "@RECEIVE@"
queue = "@RECEIVE@-rmf_schedule"
routing_key = ""
exchange_kind = "fanout"

[app]
template_directory = "diagrams/lab_examples"
